---
title: "Projects"
description: "Ousmane Diallo - Projects | Learn about my recent research projects and clinical programming work here."
author: "Ousmane DIALLO"
format:
  html:
    toc: true
    code-fold: true
highlight-style: pygments
---

# Projects

**Author**  
Ousmane Diallo, MPH-PhD

**Keywords**  
biostatistics, epidemiology, CDISC standards, clinical trials programming, real-world evidence, statistical modeling, regulatory compliance, SAS & R programming

## CDISC & Regulatory Programming
*Industry-standard clinical programming and regulatory-compliant datasets for pharmaceutical submissions*

[End-to-end Study Data Tabulation Model](projects/cdisc-sdtm.html)

[ADaM BDS Derivations for Efficacy & Safety](projects/ADaM BDS Derivations for Efficacy & Safety.html)

[Tables Listings and Figures](projects/Tables Listings and Figures.html)

[define.xml Generation & Validation Workflow](projects/sdtm-validation-project.html)

## HEOR Projects


[Cost-Effectiveness of the REPPOP Management Program](projects/cost-effectiveness-reppop.html)

[Cost-Utility of Lung Transplantation](projects/Cost-utility-Lung-Transplantation.html)

## Statistical Modeling & Real-World Evidence
*Advanced analytics and evidence generation for clinical decision-making*

[Patient-level risk factors for clinical malaria among children aged 2–60 months ](projects/patient-level-risk-factors-analysis.html)

[Hospital mortality and positive blood culture with Difficult-to threat, Marseille, France](projects/hospital-mortality-and-positive-blood-culture.html)

[Major discrepancy between factual AR and consumption in south of France](projects/discrepancy-AR-consumption.html)

## Geospatial Analysis & Epidemiology
*Spatial analysis and disease surveillance across West African populations*

[Risk Factors – ITN Guinea DHS 2018](projects/risk_factors.html)

[Spatio-temporal Modeling of Treatment-Seeking Coverage Using Demographic Health Surveys (DHS) Data and INLA](projects/treatment-seeking-bfa.html)

[Retrospective Analysis of Malaria Trend in Burkina Faso](projects/retrospective_analysis.html)

## Machine learning & multidimensional analysis

*Machine learning methods*

[Create seasonality archetypes using machine learning](projects/seasonality-archetypes.html)

[Predictors of Insecticide treated bed nets in Guinea](projects/predictors-itn-guinea.html)


---

*Interested in collaborating on biostatistics, epidemiology, or clinical programming projects?*

**[Contact me](contact.qmd)** *to discuss opportunities.*
